title: "Renaissance"
name: Renaissance Benchmark Suite
description: Docs and resources for the Renaissance Benchmark Suite
url: http://renaissance-benchmarks.github.io
baseUrl: http://renaissance-benchmarks.github.io
githubOrg: renaissance-benchmarks
githubRepo: renaissance
twitterHandle: renaissancejvm
relative_permalinks: false
